EXPLAIN ANALYZE -- Se 'EXPLAIN ANALYZE' não funcionar, use apenas 'EXPLAIN'
SELECT L.L_ORDERKEY,
    SUM(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)) AS revenue,
    O.O_ORDERDATE,
    O.O_SHIPPRIORITY
FROM CUSTOMER C
    JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
    JOIN LINEITEM L ON L.L_ORDERKEY = O.O_ORDERKEY
WHERE C.C_MKTSEGMENT = 'BUILDING'
    AND O.O_ORDERDATE < DATE '1995-03-15'
    AND L.L_SHIPDATE > DATE '1995-03-15'
GROUP BY L.L_ORDERKEY,
    O.O_ORDERDATE,
    O.O_SHIPPRIORITY
ORDER BY revenue DESC,
    O.O_ORDERDATE
LIMIT 10;