USE grupo10;

CREATE INDEX idx_orders_orderdate_orderkey ON orders (o_orderdate, o_orderkey)

EXPLAIN ANALYZE
SELECT
    N.N_NAME AS NATION,
    EXTRACT(YEAR FROM O.O_ORDERDATE) AS O_YEAR,
    SUM(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT) - PS.PS_SUPPLYCOST * L.L_QUANTITY) AS SUM_PROFIT
FROM
    PART P
JOIN PARTSUPP PS   ON PS.PS_PARTKEY = P.P_PARTKEY
JOIN SUPPLIER S    ON S.S_SUPPKEY = PS.PS_SUPPKEY
JOIN NATION N      ON N.N_NATIONKEY = S.S_NATIONKEY
JOIN LINEITEM L    ON L.L_PARTKEY = P.P_PARTKEY AND L.L_SUPPKEY = S.S_SUPPKEY
JOIN ORDERS O      ON O.O_ORDERKEY = L.L_ORDERKEY
WHERE
    P.P_NAME LIKE '%green%'
GROUP BY
    NATION, O_YEAR
ORDER BY
    NATION, O_YEAR DESC;

