CREATE INDEX idx_orders_custkey ON ORDERS(O_CUSTKEY);
CREATE INDEX idx_lineitem_orderkey ON LINEITEM(L_ORDERKEY);
CREATE INDEX idx_lineitem_quantity ON LINEITEM(L_QUANTITY);

EXPLAIN ANALYZE
SELECT
    C.C_NAME,
    C.C_CUSTKEY,
    O.O_ORDERKEY,
    O.O_ORDERDATE,
    O.O_TOTALPRICE,
    SUM(L.L_QUANTITY) AS TOTAL_QUANTITY
FROM
    CUSTOMER C
    JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
    JOIN LINEITEM L ON O.O_ORDERKEY = L.L_ORDERKEY
    JOIN (
        SELECT L_ORDERKEY
        FROM LINEITEM
        GROUP BY L_ORDERKEY
        HAVING SUM(L_QUANTITY) > 300
    ) BIG_ORDERS ON BIG_ORDERS.L_ORDERKEY = O.O_ORDERKEY
GROUP BY
    C.C_NAME,
    C.C_CUSTKEY,
    O.O_ORDERKEY,
    O.O_ORDERDATE,
    O.O_TOTALPRICE
ORDER BY
    O.O_TOTALPRICE DESC, O.O_ORDERDATE;